USE DATABASE CLAID_TEST_DB;
USE SCHEMA CLAID_TEST;

-- CONFIG TABLE
CREATE OR REPLACE TABLE CONFIG (
    CONFIG_ID INTEGER AUTOINCREMENT,
    PROJECT_NAME VARCHAR,
    CONFIG_JSON VARIANT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- RUN RESULTS
CREATE OR REPLACE TABLE RUN_RESULTS (
    RUN_ID VARCHAR,
    PROJECT_NAME VARCHAR,
    TEST_TABLE VARCHAR,
    TEST_TYPE VARCHAR,
    TEST_COLUMN VARCHAR,
    STATUS VARCHAR,
    ACTUAL_VALUE VARCHAR,
    EXPECTED_VALUE VARCHAR,
    ERROR_MESSAGE VARCHAR,
    RUN_TIMESTAMP TIMESTAMP,
    DURATION_MS NUMBER
);

-- RUN SUMMARY
CREATE OR REPLACE TABLE RUN_SUMMARY (
    RUN_ID VARCHAR,
    PROJECT_NAME VARCHAR,
    TOTAL_TESTS NUMBER,
    PASSED NUMBER,
    FAILED NUMBER,
    PASS_RATE FLOAT,
    RUN_TIMESTAMP TIMESTAMP,
    TOTAL_DURATION_MS NUMBER,
    TRIGGERED_BY VARCHAR
);

-- EMAIL SUBSCRIPTIONS
CREATE OR REPLACE TABLE EMAIL_SUBSCRIPTIONS (
    PROJECT_NAME VARCHAR,
    EMAIL VARCHAR,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
