CREATE OR REPLACE TABLE CLAID_TEST.EMAIL_SUBSCRIPTIONS (
    PROJECT_NAME VARCHAR,
    EMAIL VARCHAR,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE PROCEDURE CLAID_TEST.SP_ADD_EMAIL_SUBSCRIPTION(
    PROJECT_NAME VARCHAR,
    EMAIL VARCHAR
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    MERGE INTO CLAID_TEST.EMAIL_SUBSCRIPTIONS t
    USING (SELECT :PROJECT_NAME AS PROJECT_NAME, :EMAIL AS EMAIL) s
    ON t.PROJECT_NAME = s.PROJECT_NAME AND t.EMAIL = s.EMAIL

    WHEN MATCHED THEN 
        UPDATE SET IS_ACTIVE = TRUE

    WHEN NOT MATCHED THEN
        INSERT (PROJECT_NAME, EMAIL)
        VALUES (s.PROJECT_NAME, s.EMAIL);

    -- 🔥 SEND EMAIL IMMEDIATELY AFTER SUBSCRIBE
    CALL SYSTEM$SEND_EMAIL(
        'email_int',
        :EMAIL,
        'Subscription Successful ✔',
        'You are now subscribed to CLAID-TEST alerts for ' || :PROJECT_NAME
    );

    RETURN 'Subscription successful + email sent';

END;
$$;

CREATE OR REPLACE PROCEDURE CLAID_TEST.SP_UNSUBSCRIBE_EMAIL(
    PROJECT_NAME VARCHAR,
    EMAIL VARCHAR
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    UPDATE CLAID_TEST.EMAIL_SUBSCRIPTIONS
    SET IS_ACTIVE = FALSE
    WHERE PROJECT_NAME = :PROJECT_NAME
      AND EMAIL = :EMAIL;

    -- 🔔 Send confirmation email
    CALL SYSTEM$SEND_EMAIL(
        'email_int',
        :EMAIL,
        'Unsubscribed Successfully ❌',
        'You have been unsubscribed from CLAID-TEST alerts for ' || :PROJECT_NAME
    );

    RETURN 'Unsubscribed successfully + email sent';

END;
$$;
CREATE OR REPLACE TABLE CLAID_TEST.EMAIL_SUBSCRIPTIONS AS
SELECT * FROM EMAIL_SUBSCRIPTIONS;
DROP TABLE EMAIL_SUBSCRIPTIONS;
DELETE FROM CLAID_TEST.EMAIL_SUBSCRIPTIONS;
INSERT INTO CLAID_TEST.EMAIL_SUBSCRIPTIONS (
    PROJECT_NAME,
    EMAIL,
    IS_ACTIVE
)
VALUES (
    'SAMPLE_PROJECT',
    'sharmaishita026@gmail.com',
    TRUE
);

CALL CLAID_TEST.SP_ADD_EMAIL_SUBSCRIPTION(
    'SAMPLE_PROJECT',
    'sharmaishita026@gmail.com'
);
CREATE OR REPLACE NOTIFICATION INTEGRATION email_int
TYPE = EMAIL
ENABLED = TRUE;
-- Email integration

SHOW INTEGRATIONS LIKE 'email_int';
-- Subscription table
SELECT * FROM CLAID_TEST.EMAIL_SUBSCRIPTIONS;
ALTER NOTIFICATION INTEGRATION email_int 
SET ALLOWED_RECIPIENTS = ('sharmaishita026@gmail.com');


CALL SYSTEM$SEND_EMAIL(
    'email_int',
    'sharmaishita026@gmail.com',
    'CLAID TEST',
    'Final test — should work now 🚀'
);
SHOW USERS;

-- ============Verify email integration============
SHOW INTEGRATIONS LIKE 'EMAIL_INT';
DESC INTEGRATION EMAIL_INT;


CALL CLAID_TEST.SP_RUN_TESTS(
    'SAMPLE_PROJECT',
    'MANUAL'
);



