-- ======SCHEDULE=======
SHOW TASKS;
CREATE OR REPLACE TASK TASK_SAMPLE_PROJECT
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON */5 * * * * Asia/Kolkata'
AS 
CALL CLAID_TEST.SP_RUN_TESTS('SAMPLE_PROJECT', 'SCHEDULED');
ALTER TASK TASK_SAMPLE_PROJECT RESUME;
-- =========24 hours=====================================
CREATE OR REPLACE TASK CLAID_TEST.TASK_SAMPLE_PROJECT
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 0 * * * Asia/Kolkata'
AS 
CALL CLAID_TEST.SP_RUN_TESTS('SAMPLE_PROJECT', 'SCHEDULED');
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'TASK_SAMPLE_PROJECT'
ORDER BY SCHEDULED_TIME DESC;
